---

- name: Enable WireGuard kernel module
  modprobe:
    name: wireguard
    state: present
  register: wireguard_module_enabled
  until:  wireguard_module_enabled is succeeded
  retries: 10
  delay: 10
  failed_when: wireguard_module_enabled is failure
  tags:
    - wireguard-install

- name: Configure {{ item }}
  template:
    src: wgX.conf.j2
    dest: /etc/wireguard/{{ item }}.conf
    mode: 0600
  register: configuration

- name: Enable wg-quick@{{ item }} service
  systemd:
    name: wg-quick@{{ item }}
    state: started
    enabled: yes
  tags: install
  when: wireguard_manage_services

- name: Restart wg-quick@{{ item }}
  systemd:
    name: wg-quick@{{ item }}
    state: restarted
  when: configuration is changed and wireguard_manage_services
